"""empty message

Revision ID: 089755bbb454
Revises: 74662d1be27b
Create Date: 2020-05-05 14:15:17.937939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089755bbb454'
down_revision = '74662d1be27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('''
        UPDATE todos 
        SET completed = False 
        WHERE completed IS NULL;
        ''')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
