"""empty message

Revision ID: 74662d1be27b
Revises: 
Create Date: 2020-05-05 14:10:29.970457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74662d1be27b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
